# Generated by Django 5.0.2 on 2026-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('up_next', 'Up Next'), ('complete', 'Complete')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='series_order',
            field=models.IntegerField(blank=True, help_text='Chapter or episode number within the book/podcast series.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.guest'),
        ),
        migrations.AddField(
            model_name='guest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='guests', to='blog.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag'),
        ),
    ]
